### ISSUE TITLE
No resources folder cached

### ISSUE THREAD

**Issue by nolafs** [cdeleeuwe/netlify-plugin-hugo-cache-resources#5]
Seems this plugin is not working for me. I got massive resource folder when building it in productions, so i know the folder is there. It is under sub directory of site. When the plugin runs, it cannot find the resources folder. No resources folder cached message.

**Comment by cdeleeuwe** [comment]
Hi @nolafs, are you using Hugo's --gc option for your build? If yes, I think that option makes Hugo cleanup the cached resources after the build. If not, can you share the Netlify logs?

**Comment by nolafs** [comment]
My production build does not use --gc option

 "build:hugo": "hugo -d ../dist --minify -s site -v"

I think it has to with my project structure as I am using webpack, I am having the hugo source code under sub-directory called site. So my guess is that it cannot find the resource folder as the plugin expect it on the root of the project. Would be possible to add option to define the location of the resource folder?

Cheers
Olaf

**Comment by cdeleeuwe** [comment]
@nolafs aah OK, yes that makes sens :). Sure, sounds good, I will add an option to define the location.

**Comment by cdeleeuwe** [comment]
@nolafs I just pushed a solution for this. Feel free to pull the latest NPM package or wait for Netlify to merge the latest version. And let me know if it works for you?

**Comment by nolafs** [comment]
@cdeleeuwe Thanks, great.
