### ISSUE TITLE
Total Files Generated: 2 - Is this working correctly?

### ISSUE THREAD

**Issue by jpinto3488** [cdeleeuwe/netlify-plugin-hugo-cache-resources#9]
Hello, I installed this plugin on Netlify for a HUGO based website.
The deployment is configured as follows:
Base directory: not set
Build command: hugo
Publish directory: public

7:06:57 PM:   1. onPreBuild command from netlify-plugin-hugo-cache-resources  
When I run a deployment on the logs I see the following:
7:06:58 PM: Checking if resources exist at "resources"
7:06:58 PM: Restored cached resources folder. Total files: 2
7:06:58 PM: ---
7:06:58 PM: 1. /opt/build/repo/resources
7:06:58 PM: 2. /opt/build/repo/resources/_gen

[... Hugo Builds...]

7:07:01 PM:   3. onPostBuild command from netlify-plugin-hugo-cache-resources  
7:07:01 PM: ───────────────────────────────────────────────────────────────────
7:07:01 PM: ​
7:07:02 PM: Saved resources folder to cache. Total files: 2
7:07:02 PM: ---
7:07:02 PM: 1. /opt/build/repo/resources
7:07:02 PM: 2. /opt/build/repo/resources/_gen
7:07:02 PM: ​
7:07:02 PM: (netlify-plugin-hugo-cache-resources onPostBuild completed in 609ms)

I know the resources/_gen folder has about 400 generated images, so why it says "Total files:2"? Is the plugin not working for some reason?
How can I see if it is working correctly?

Thank you

**Comment by cdeleeuwe** [comment]
Hi @jpinto3488 thanks for noticing this. I think it's just an issue with the logging. It only logs the count of the files/folders directly under the /resources folder (not sub-files/folders). But he images are actually cached correctly. 

Will push a fix later this week.
